/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/components/BackendTechOverView': RouteRecordInfo<'/home/components/BackendTechOverView', '/home/components/BackendTechOverView', Record<never, never>, Record<never, never>>,
    '/home/components/DescripPage': RouteRecordInfo<'/home/components/DescripPage', '/home/components/DescripPage', Record<never, never>, Record<never, never>>,
    '/home/components/FrontTechOverView': RouteRecordInfo<'/home/components/FrontTechOverView', '/home/components/FrontTechOverView', Record<never, never>, Record<never, never>>,
    '/home/components/MaskPage': RouteRecordInfo<'/home/components/MaskPage', '/home/components/MaskPage', Record<never, never>, Record<never, never>>,
    '/home/components/PlanetPage': RouteRecordInfo<'/home/components/PlanetPage', '/home/components/PlanetPage', Record<never, never>, Record<never, never>>,
    '/home/components/ScaleVideoPage': RouteRecordInfo<'/home/components/ScaleVideoPage', '/home/components/ScaleVideoPage', Record<never, never>, Record<never, never>>,
    '/home/components/SolarPage': RouteRecordInfo<'/home/components/SolarPage', '/home/components/SolarPage', Record<never, never>, Record<never, never>>,
    '/home/components/TreePage': RouteRecordInfo<'/home/components/TreePage', '/home/components/TreePage', Record<never, never>, Record<never, never>>,
  }
}
